In [1]:
import cv2

In [2]:
import imutils

In [4]:
from PIL import Image
img = Image.open("/home/jetson/projects/crowd-thermometer/images/frames_ir/00001.jpg")

In [24]:
net = cv2.dnn.readNetFromCaffe("deploy.prototxt.txt", "res10_300x300_ssd_iter_140000.caffemodel")
net.setPreferableBackend(cv2.dnn.DNN_BACKEND_CUDA)
net.setPreferableTarget(cv2.dnn.DNN_TARGET_CUDA)

In [25]:
frame = arr

In [26]:
blob = cv2.dnn.blobFromImage(
    cv2.resize(frame, (300, 300)),
    1.0,
    (300, 300),
    (104.0, 177.0, 123.0)
    )
net.setInput(blob)
detections = net.forward()

In [46]:
# from shape (1,1,200,7) to (200,7)
detections = np.squeeze(detections)

(600, 800)

array([[0.        , 1.        , 0.21951902, 2.1079738 , 2.0746481 ,
        2.8868082 , 2.90435   ]], dtype=float32)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [49]:
detections[0]

array([0.        , 1.        , 0.21951902, 2.1079738 , 2.0746481 ,
       2.8868082 , 2.90435   ], dtype=float32)

In [47]:
for d in detections:

array([[0.        , 1.        , 0.21951902, ..., 2.0746481 , 2.8868082 ,
        2.90435   ],
       [0.        , 1.        , 0.18087958, ..., 0.39476937, 1.2387309 ,
        1.2478969 ],
       [0.        , 1.        , 0.1452076 , ..., 1.1507685 , 2.9443216 ,
        1.8922718 ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]], dtype=float32)

The slowest run took 6.52 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 4.7 µs per loop


In [34]:
detections

AttributeError: 'numpy.ndarray' object has no attribute 'unravel'

In [33]:
detections[:,:,0,:]

array([[[0.        , 1.        , 0.21951902, 2.1079738 , 2.0746481 ,
         2.8868082 , 2.90435   ]]], dtype=float32)

In [5]:
?cv2.resize

In [6]:
import numpy as np

In [8]:
arr.shape

(600, 800, 3)

In [20]:
%timeit i = 

100 loops, best of 3: 2.37 ms per loop
